version: '3'

services:
    scheduler:
        build: ./backend
        restart: always
        env_file: .env
        volumes:
            - ./downloaded_files:/backend/IRIS_seismic_data/downloaded_files
    app:
        build: ./app
        restart: always
        env_file: .env
        ports: 
          - 8050:8050
        depends_on: 
          - scheduler
        volumes:
            - ./app:/app
            - ./downloaded_files:/app/IRIS_seismic_data
