version: '3'

services:
    scheduler:
        build: ./backend
        restart: always
        #env_file: .env
        volumes:
            - ./database:/backend/database
            - ./logs:/backend/logs
    app:
        build: ./app
        restart: always
        #env_file: .env
        ports: 
          - 8050:8050
        depends_on: 
          - scheduler
          - redis
        volumes:
            - ./app:/app
            - ./database:/app/database
            - ./logs:/app/logs      
    redis:
        image: "redis:latest"
        ports:
          - "6379:6379"

