version: '3'

services:
    scheduler:
        build: ./backend
        restart: always
        volumes:
            - ./database:/backend/database
            - ./logs:/backend/logs
            - ./.env:/backend/.env
    app:
        build: ./app
        restart: always
        ports: 
          - 8080:8080
        depends_on: 
          - scheduler
          - redis
        volumes:
            - ./app:/app
            - ./database:/app/database
            - ./logs:/app/logs 
            - ./.env:/app/.env
    redis:
        image: "redis:latest"
        ports:
          - "6379:6379"

